name: Autograding

on: 
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up C Compiler
      - name: Set up C Compiler
        run: sudo apt-get install build-essential

      # Step 3: Compile student code
      - name: Compile student code
        run: g++ -o student_program student_program.cpp

      # Step 4-13: Run Test Cases 1-10 and Calculate Percentage
      - name: Run and Compare Test Cases
        run: |
          total_testcases=0
          passed_testcases=0
          
          for i in $(seq 1 10); do
            if [ -f testcases/input${i}.dat ]; then
              # Increment total test cases count
              total_testcases=$((total_testcases+1))
              
              # Run Test Case
              ./student_program < testcases/input${i}.dat > output${i}.txt
              
              # Compare Test Case
              if [ -f testcases/output${i}.dat ]; then
                if grep -Fq "$(cat testcases/output${i}.dat)" output${i}.txt; then
                  # Print passed test case in green
                  echo -e "\033[0;32mTest Case ${i} Passed\033[0m"
                  passed_testcases=$((passed_testcases+1))
                else
                  # Print failed test case in red
                  echo -e "\033[0;31mTest Case ${i} Failed\033[0m"
                  # Show differences between expected and actual output
                  echo -e "\033[0;31mDifferences:\033[0m"
                  diff testcases/output${i}.dat output${i}.txt || true
                fi
              else
                echo "Test Case ${i} skipped (no output file found)."
              fi
            else
              echo "Test Case ${i} skipped (no input file found)."
            fi
          done
          
          # Calculate Score as Percentage
          if [ $total_testcases -gt 0 ]; then
            score=$(( (passed_testcases * 100) / total_testcases ))
          else
            score=0
          fi
          
          echo "Total Test Cases: $total_testcases"
          echo "Passed Test Cases: $passed_testcases"
          echo "Score Percentage: $score%"
          echo "SCORE=$score" >> $GITHUB_ENV

      # Step 14: Extract student info
      - name: Extract student info
        id: student_info
        run: |
          source student_info.txt
          echo "STUDENT_ID=${student_id}" >> $GITHUB_ENV
          echo "SUBJECT_ID=${subject_id}" >> $GITHUB_ENV
          echo "TERM=${term}" >> $GITHUB_ENV

      # Step 15: Extract lab_id from github_repo
      - name: Extract lab_id from github_repo
        id: extract_lab_id
        run: |
          LAB_ID=$(echo "${{ github.repository }}" | awk -F'/' '{print $2}' | awk -F'-' '{print $1}')
          echo "LAB_ID=$LAB_ID" >> $GITHUB_ENV

      # Step 16: Send results to the website
      - name: Records results
        if: ${{ success() }}  # Runs only if all previous steps succeeded
        run: |
          TIMESTAMP=$(TZ='Asia/Bangkok' date +"%Y-%m-%dT%H:%M:%S%z")
          curl -X POST -H "Content-Type: application/json" \
          -d '{
            "student_id": "${{ env.STUDENT_ID }}",
            "subject_id": "${{ env.SUBJECT_ID }}",
            "term": "${{ env.TERM }}",
            "lab_id": "${{ env.LAB_ID }}",
            "github_username": "${{ github.actor }}",
            "github_repo": "${{ github.repository }}",
            "timestamp": "'"$TIMESTAMP"'",
            "score": "${{ env.SCORE }}"
          }' \
          https://www.thailandfxwarrior.com/get_student_info.php

